import React from 'react';
import './global.css';
import 'react-toastify/dist/ReactToastify.css';
import ToastHoc from '../containers/ToastHoc/ToastContainer';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <main>
      <ToastHoc>{children}</ToastHoc>
    </main>
    </body>
    </html>
  );
}
